name: Compilation TWRP Serenity

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Nettoyer espace disque
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/share/boost "$AGENT_TOOLSDIRECTORY"

    - name: Outils de compilation
      run: |
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev libncurses5-dev libx11-dev lib32z1-dev libxml2-utils xsltproc unzip rsync python3 repo

    - name: Sources TWRP Android 14
      run: |
        mkdir twrp && cd twrp
        repo init --depth=1 -u https://github.com -b twrp-14.1
        repo sync -c -j$(nproc) --force-sync --no-clone-bundle --no-tags

    - name: Injection Device Tree
      run: |
        mkdir -p twrp/device/xiaomi/serenity
        curl -sL https://github.com{{ github.repository }}/archive/refs/heads/main.tar.gz | tar -xz -C twrp/device/xiaomi/serenity --strip-components=1

    - name: Compilation
      run: |
        cd twrp
        . build/envsetup.sh
        lunch twrp_serenity-eng
        mka recoveryimage -j$(nproc)

    - name: Upload du fichier final
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-Redmi-A5
        path: twrp/out/target/product/serenity/recovery.img
